# Generated by Django 5.1.8 on 2025-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('food_1', models.CharField(blank=True, max_length=100)),
                ('food_2', models.CharField(blank=True, max_length=100)),
                ('food_3', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
