# Generated by Django 5.1.8 on 2025-04-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='food_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='food_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='food_3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
