language: python
framework: django
runtime: python3.10
startup_file: startup.sh
env_vars:
  - name: DJANGO_SECRET_KEY
    value: ${{ secrets.DJANGO_SECRET_KEY }}
  - name: OPENAI_API_KEY
    value: ${{ secrets.OPENAI_API_KEY }}
  - name: WEBSITES_PORT
    value: 8000
  - name: SCM_DO_BUILD_DURING_DEPLOYMENT
    value: true
  - name: DJANGO_SETTINGS_MODULE
    value: chatbot_project.settings 