name: Deploy Django API to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: food-chatbot-app-api
  PYTHON_VERSION: '3.10'
  WORKING_DIRECTORY: '.'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv antenv
        source antenv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gunicorn whitenoise

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: '.azurewebsites.net'

    - name: Run database migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate --noinput
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: '.azurewebsites.net'

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        zip -r deployment.zip . -x "antenv/*" "*.git*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip

    - name: Clean up deployment package
      run: rm deployment.zip

    - name: Verify deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 30
        response_code=$(curl -s -o /dev/null -w "%{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/)
        if [ "$response_code" != "200" ]; then
          echo "Deployment verification failed with status code: $response_code"
          exit 1
        fi 