name: Deploy Django API to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: food-chatbot-app-api
  PYTHON_VERSION: '3.10'
  WORKING_DIRECTORY: '.'  # Set to root directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Check directory structure
      run: |
        pwd
        ls -la
        echo "Current working directory: $(pwd)"
        echo "Requirements file exists: $(test -f requirements.txt && echo 'Yes' || echo 'No')"

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Collect static files
      run: |
        python manage.py collectstatic --noinput
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY || 'temporary-secret-key-for-build' }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'dummy-key-for-build' }}
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.WORKING_DIRECTORY }} 